version: '3'
services:
  app:
    image: formation:latest
    build:
      context: .
    environment:
      - DB_HOST=database:5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_SCHEMA=postgres
      - SWAGGER_CLIENT_ID=toto
      - SWAGGER_SECRET_ID=titi
    ports:
      - 8080:8080
    links:
      - db:database
    depends_on:
      - db
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
