server:
  servlet:
    context-path: /demo
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_empty

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    #https://github.com/pgjdbc/pgjdbc/issues/1102
    properties:
      hibernate:
        jdbc:
          time_zone: Europe/Paris
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_SCHEMA:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: postgres

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, env, prometheus, swagger, health

info:
  app:
    name: @project.name@
    version: @project.version@
